# Generated by Django 4.1 on 2022-09-02 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clase_Familia',
            new_name='Familiar',
        ),
    ]
